### ISSUE TITLE
"true" value for <nullable> causes compilation to fail on VS2019

### ISSUE THREAD

**Issue by skacurt** [ssg/TurkishId#4]
https://github.com/ssg/TurkishId/blob/1627d7cb0039d3a22f60b440a0d84e1401978e5a/src/TurkishId/TurkishId.csproj#L23

https://github.com/ssg/TurkishId/blob/1627d7cb0039d3a22f60b440a0d84e1401978e5a/src/TurkishIdGen/TurkishIdGen.csproj#L10

https://github.com/ssg/TurkishId/blob/1627d7cb0039d3a22f60b440a0d84e1401978e5a/test/TurkishIdTest.csproj#L8

VS2019 is complaining about the `true`s.

> CSC : error CS8636: Invalid option 'true' for /nullable; must be 'disable', 'enable', 'warnings' or 'annotations'

As you can see in the error message, according to https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts valid settings are `enable`, `warnings`, `annotations` and `disable`.

With `<Nullable>enable</Nullable>`s, all three projects are compiled successfully in both VS2017 and VS2019, and the test completed with no errors. So, it seems like `enable` is forward-compatible.

This recent .NET Framework/Core/Standard things confuses me a lot, don't know if there's and edge case here. What's your thoughts, would a PR be OK?

**Comment by ssg** [comment]
Microsoft decided to change syntax over and over during the development of C# 8.0 that's why it was failing. It should work now, thanks!
